# config.yaml
pipeline:
  filedirectory: "./data/"
  max_pages: 5
  max_limit: 100

jobs:
  - title: "Data Scientist"
    location: "Bangalore"
  - title: "ML Engineer"
    location: "Remote"

storage:
  type: "csv"
  filename: "jobs_output.csv"

version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(levelname)s: %(message)s"
  detailed:
    format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log
    mode: a

loggers:
  data_collection:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]
